# Generated by Django 2.2.2 on 2019-06-30 04:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_remove_post_mark'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='mark',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
